<?php

function crashndash_menu() {
  $items['admin/config/services/crashndash'] = array(
    'title' => 'Crash n Dash settings',
    'description' => 'Settings to make Crash n Dash site work.',
    'route_name' => 'crashndash.admin_settings',
  );
  $items['frontpage'] = array(
    'title' => 'Crash n Dash',
    'description' => 'The front page of the site.',
    'route_name' => 'crashndash.frontpage',
  );
  $items['world-high-scores'] = array(
    'title' => 'Crash n Dash',
    'description' => 'The world high scores.',
    'route_name' => 'crashndash.high_scores',
  );
  return $items;
}

function crashndash_theme() {
  return array(
    'crashndash_frontpage' => array(
      'path' => drupal_get_path('module', 'crashndash'),
      'template' => 'crashndashfrontpage',
      'variables' => array('vars' => NULL),
    ),
    'crashndash_play' => array(
      'path' => drupal_get_path('module', 'crashndash'),
      'template' => 'crashndashplay',
      'variables' => array('vars' => NULL),
    ),
  );
}
