<?php

/**
 * @file
 * Crashnash module.
 */

define('CRASHNDASH_DATA_KEY', 'crashndash.data');

/**
 * Implements hook_theme().
 */
function crashndash_theme() {
  return [
    'crashndash_frontpage' => [
      'path' => drupal_get_path('module', 'crashndash'),
      'template' => 'crashndashfrontpage',
      'variables' => [
        'rooms' => [],
        'users' => 0,
        'room_update' => 0,
        'updated_raw' => '',
      ],
    ],
    'crashndash_play' => [
      'path' => drupal_get_path('module', 'crashndash'),
      'template' => 'crashndashplay',
      'variables' => [
        'referrer' => '',
        'room' => 0,
      ],
    ],
  ];
}
